### ISSUE TITLE
fix: Generator tries to fit all variable collections into one class

### ISSUE THREAD

**Issue by JesperBllnbm** [whynotmake-it/figmage#40]
**Description**

It looks like that the generator tries to create just 1 class to fit all collections. 
For example if a core token collection exist:
<img width="985" alt="image" src="https://github.com/whynotmake-it/figmage/assets/31738080/1e90819a-83ff-4678-b626-c7003957b185">

The Color class looks like that: 

```dart
...
class Colors extends ThemeExtension<Colors> {
  const Colors({
    required this.color,
    required this.blue500,
    required this.blue800,
    required this.red500,
    required this.red800,
  });
...
```

If another collection like this exists:
<img width="837" alt="image" src="https://github.com/whynotmake-it/figmage/assets/31738080/2c6f8933-d7c3-4431-9116-ede688afbdc5">

The generator tries to reuse the Color class from the Core collection (which fails):

```dart
...
  const Colors.$284()
      : color = const Color(0xff000000),
        colorWith2Aliases = const Color(0xff000000),
        colorWithAlias = const Color(0xff000000);
...
```

**Comment by timcreatedit** [comment]
That's exactly what's happening, there's no mechanism for creating multiple classes rn 😅
